### ISSUE TITLE
UnrecognizedFlagError!!

### ISSUE THREAD

**Issue by yzho0907** [FrankWork/fudan_mtl_reviews#1]
Traceback (most recent call last):
  File "src/main.py", line 7, in <module>
    from inputs import util
  File "/home/young/Downloads/fudan_mtl_reviews-master/src/inputs/util.py", line 50, in <module>
    def write_vocab(vocab, vocab_file=FLAGS.vocab_file):
  File "/home/young/Downloads/ENTER/envs/deeplearning/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/young/Downloads/ENTER/envs/deeplearning/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 630, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'build_data'

any idea how to fix it?

**Comment by yzho0907** [comment]
thx, but missing embed300.trim.npy?

**Comment by wangzhihuia** [comment]
I am also trying to find solutions to solve this problem...

**Comment by yzho0907** [comment]
is the embed300.trim.npy a word2vec?

**Comment by FrankWork** [comment]
`embed300.trim.npy` is trimmed from [google news word2vec](https://drive.google.com/file/d/0B7XkCwpI5KDYNlNUTTlSS21pQmM/edit?usp=sharing)

**Comment by FrankWork** [comment]
you can use `--word_dim=50` to  use pre-trained 50 dim senna embeddings

**Comment by yzho0907** [comment]
thank u very much. i would like to try to change the data-set to a Chinese data-set, a lot of work to do!

**Comment by xiaoleihuang** [comment]
@wangzhihuia @FrankWork I tried the both commands below:
1. `python src/main.py build_data --word_dim=300`;
2. `python src/main.py --word_dim=300 --build_data`;

I still got the following error:
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'word_dim'

Could you help me? Thank you!

<b><font color="red">Solved</font></b>
Changed the settings in the main() codes:
1. Change all 300 dims into 50
2. Create two directories: `saved_models` in the project root folder; in `data` folder, create `generated'; in the `saved_models` folder create `fudan-mtl-adv`

**Comment by shizi626** [comment]
There are so many missing file in this project.
These files are all defined in `util.py`, from line 11 to line 32
```
flags.DEFINE_string("vocab_file", "data/generated/vocab.mtl.txt", 
                              "vocab of train and test data")

flags.DEFINE_string("google_embed300_file", 
                             "data/pretrain/embed300.google.npy", 
                             "google news word embeddding")
flags.DEFINE_string("google_words_file", 
                             "data/pretrain/google_words.lst", 
                             "google words list")
flags.DEFINE_string("trimmed_embed300_file", 
                             "data/generated/embed300.trim.npy", 
                             "trimmed google embedding")

flags.DEFINE_string("senna_embed50_file", 
                             "data/pretrain/embed50.senna.npy", 
                             "senna words embeddding")
flags.DEFINE_string("senna_words_file", 
                             "data/pretrain/senna_words.lst", 
                             "senna words list")
flags.DEFINE_string("trimmed_embed50_file", 
                             "data/generated/embed50.trim.npy", 
                             "trimmed senna embedding")
```
How and where can I find these files?
Or how can I convert the original word embedding files to the correct format?

**Comment by linxiaoby** [comment]
I remove all the flags.DEFINE in util.py, and it works. Maybe  it is because only one file can has flags?

**Comment by p-null** [comment]
Hi, I tried every the method above. I still got the ` Unknown command line flag` error.
Can someone provide a step-by-step procedure to run this program?

ps. I have also tried the exactly what author said in the readme but its not working.

**Comment by yzho0907** [comment]
plz give the full error and Traceback

**Comment by chenting0324** [comment]
Hi, how can I use a Chinese data set? How to train the file "embed300.trim.npy"

**Comment by yzho0907** [comment]
.npy file is actually a numpy type file, once u traind a 300d word embedding u can save it to a numpy type by using np.save() but more suggest that u use gensim.
Using Chinese data set i highly suggest u follow author's training data format and run the code. there is a another repo https://github.com/andyweizhao/capsule_text_classification gained a higher score.
